import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "../../components/banner/banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Netflix</h1>

      {/* <NavBar /> */}
      <Banner
        title="The Inglorious Bastards"
        subTitle="a very cute dog"
        imgUrl="/static/inglorious_bastards.png"
      />
      {/* <Card /> */}
    </>
  );
}
